/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'gst' : IDL.Nat,
  'hsn' : IDL.Text,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
});
export const BillId = IDL.Nat;
export const LineItem = IDL.Record({
  'gst' : IDL.Nat,
  'hsn' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'gstAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Bill = IDL.Record({
  'id' : BillId,
  'customerName' : IDL.Opt(IDL.Text),
  'lineItems' : IDL.Vec(LineItem),
  'date' : Timestamp,
  'gstAmount' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'customerAddress' : IDL.Opt(IDL.Text),
  'billNumber' : IDL.Text,
  'customerId' : IDL.Opt(CustomerId),
  'subtotal' : IDL.Nat,
});
export const ProducerSettings = IDL.Record({
  'ifscCode' : IDL.Text,
  'gstNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'authorisedSignatory' : IDL.Text,
  'accountNumber' : IDL.Text,
  'accountHolder' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [Product],
      [],
    ),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getProducerSettings' : IDL.Func([], [IDL.Opt(ProducerSettings)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
  'listBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveBill' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(CustomerId),
        IDL.Opt(IDL.Text),
        IDL.Vec(LineItem),
      ],
      [Bill],
      [],
    ),
  'setProducerSettings' : IDL.Func([ProducerSettings], [], []),
  'updateCustomer' : IDL.Func(
      [CustomerId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'gst' : IDL.Nat,
    'hsn' : IDL.Text,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const BillId = IDL.Nat;
  const LineItem = IDL.Record({
    'gst' : IDL.Nat,
    'hsn' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'gstAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Bill = IDL.Record({
    'id' : BillId,
    'customerName' : IDL.Opt(IDL.Text),
    'lineItems' : IDL.Vec(LineItem),
    'date' : Timestamp,
    'gstAmount' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'customerAddress' : IDL.Opt(IDL.Text),
    'billNumber' : IDL.Text,
    'customerId' : IDL.Opt(CustomerId),
    'subtotal' : IDL.Nat,
  });
  const ProducerSettings = IDL.Record({
    'ifscCode' : IDL.Text,
    'gstNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'authorisedSignatory' : IDL.Text,
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [Product],
        [],
      ),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getProducerSettings' : IDL.Func(
        [],
        [IDL.Opt(ProducerSettings)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
    'listBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveBill' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(CustomerId),
          IDL.Opt(IDL.Text),
          IDL.Vec(LineItem),
        ],
        [Bill],
        [],
      ),
    'setProducerSettings' : IDL.Func([ProducerSettings], [], []),
    'updateCustomer' : IDL.Func(
        [CustomerId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };