/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : BillId,
  'customerName' : [] | [string],
  'lineItems' : Array<LineItem>,
  'date' : Timestamp,
  'gstAmount' : bigint,
  'grandTotal' : bigint,
  'customerAddress' : [] | [string],
  'billNumber' : string,
  'customerId' : [] | [CustomerId],
  'subtotal' : bigint,
}
export type BillId = bigint;
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type CustomerId = bigint;
export interface LineItem {
  'gst' : bigint,
  'hsn' : string,
  'productId' : ProductId,
  'productName' : string,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'price' : bigint,
  'amount' : bigint,
}
export interface ProducerSettings {
  'ifscCode' : string,
  'gstNumber' : string,
  'bankName' : string,
  'address' : string,
  'companyName' : string,
  'authorisedSignatory' : string,
  'accountNumber' : string,
  'accountHolder' : string,
}
export interface Product {
  'id' : ProductId,
  'gst' : bigint,
  'hsn' : string,
  'name' : string,
  'stock' : bigint,
  'price' : bigint,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, string, string], Customer>,
  'addProduct' : ActorMethod<[string, bigint, bigint, bigint, string], Product>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getBill' : ActorMethod<[BillId], [] | [Bill]>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getProducerSettings' : ActorMethod<[], [] | [ProducerSettings]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listBills' : ActorMethod<[], Array<Bill>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'saveBill' : ActorMethod<
    [[] | [string], [] | [CustomerId], [] | [string], Array<LineItem>],
    Bill
  >,
  'setProducerSettings' : ActorMethod<[ProducerSettings], undefined>,
  'updateCustomer' : ActorMethod<[CustomerId, string, string, string], boolean>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, bigint, bigint, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];